M48
; DRILL file {KiCad 7.0.5} date Wed Aug  9 22:54:26 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-09T22:54:26+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X-20.11Y21.59
X-4.87Y21.59
T2
X-22.0Y27.0
X-22.0Y-27.0
X22.0Y27.0
X22.0Y-27.0
T0
M30
